BEGIN;

UNLOAD
($$
SELECT 
	SCHEMANAME||'.'||TABLENAME 
FROM PG_TABLES 
WHERE UPPER(SCHEMANAME) <> 'INFORMATION_SCHEMA' 
	AND UPPER(SCHEMANAME) NOT LIKE 'PG_%'
ORDER BY 1
$$)
TO :S3TXT
access_key_id :AWS_KEY
secret_access_key :AWS_SECRET
ALLOWOVERWRITE
PARALLEL OFF;

COMMIT;